name = "Alive"
default_targets = ["win32", "win64", "appimage"]
build_directory = "makelove-build"

love_files = [
    "::git-ls-tree::",
    "-*/.*",
]

[archive_files]
"license.txt" = "license.txt"
"love_license.txt" = "love_license.txt"
